services:
  text-analysis-agent:
    container_name: a2a-text-analysis-agent
    build:
      context: .
    ports:
      - "${A2A_SERVER_PORT:-10002}:${A2A_SERVER_PORT:-10002}"
    env_file:
      - .env
    environment:
      - A2A_SERVER_HOST=${A2A_SERVER_HOST:-0.0.0.0}
      - A2A_SERVER_PORT=${A2A_SERVER_PORT:-10002}
      - AGENT_URL=${AGENT_URL:-http://host.docker.internal:10002/}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - a2a-network

networks:
  a2a-network:
    driver: bridge 